import json
src=json.load(open('/tmp/arxiv-candidates.json'))['papers']
chosen=[0,3,8,11,17,21,56,83,84,88]
notes={
0:("The authors prove that approximate k-designs can be generated with optimal polylogarithmic depth using only the system qubits, eliminating the usual ancillary-qubit overhead. Their construction combines random local circuits with a rigorous design analysis and gives depth scaling near-linear in k up to polylogarithmic factors, an important resource result for benchmarking and randomized quantum algorithms.","Directly relevant to scalable randomization, quantum learning, and classical-shadow-style protocols where ancilla space is costly.",["random-circuits","unitary-designs","quantum-resources"]),
3:("This model combines a timelike Randall–Sundrum brane with a kinetically coupled entropic mechanism to produce a nonsingular cyclic cosmology. The authors show how the same construction can regularize the bounce, generate an acceptable scalar spectrum, and control entropy growth across cycles, addressing several standard ekpyrotic obstacles in one dynamical setup.","Relevant to quantum-gravity-informed cosmology: it is an explicit testbed for bounce resolution, extra-dimensional effects, and alternatives to inflation.",["cyclic-cosmology","brane-worlds","ekpyrotic-bounce"]),
8:("The experiment distributes ion–photon entanglement through a 2.8 km deployed fiber while ordinary Ethernet and 5G traffic share the same fiber. By characterizing noise, synchronization, and entanglement quality under live telecom conditions, the work demonstrates that trapped-ion networking need not be confined to dedicated dark fiber.","A concrete systems result for quantum networks, showing how existing telecommunications infrastructure can lower deployment barriers.",["quantum-networks","trapped-ions","telecom-coexistence"]),
11:("For boundary gravitons in AdS3, the authors formulate a finite-moment tomography protocol based on boundary stress-tensor measurements. Under finite descendant support and nondegenerate Shapovalov forms, they identify when these moments recover interlevel coherences, turning abstract Virasoro-state information into an operational reconstruction problem.","Connects holographic boundary observables with information recovery and provides a sharp laboratory for quantum-gravity tomography.",["AdS3-gravity","boundary-gravitons","quantum-tomography"]),
17:("The paper constructs electronic-Hamiltonian time-evolution circuits directly in second quantization, avoiding expansion into Pauli strings. A ladder-string-pair diagonalization handles general complex coefficients and exposes fermionic structure that standard mappings obscure, reducing compilation overhead for simulation circuits.","Useful for quantum chemistry and many-body simulation: it targets a central source of circuit growth in fault-tolerant quantum computing.",["quantum-simulation","electronic-structure","circuit-compilation"]),
21:("Using gauge- and Lorentz-invariant Wilson-line-dressed scalar operators, the authors compute finite-time and finite-distance overlaps in scalar QED with a controlled Stueckelberg infrared regulator. The perturbative result makes superselection, soft-photon dressing, and infraparticle behavior explicit in a calculable Euclidean-gluing framework.","Highly relevant to the infrared structure of gauge theory and the relation between quantum information in charged sectors and asymptotic observables.",["scalar-QED","infraparticles","infrared-physics"]),
56:("The authors analyze one-dimensional quantum walks with symmetries that protect edge modes against perturbations. By combining bulk topological invariants with boundary-state calculations, they identify conditions for robust localized modes and characterize their transport response, supplying a controllable platform for topological quantum dynamics.","Bridges quantum information and condensed matter through experimentally accessible topological walks and protected boundary information.",["topological-phases","quantum-walks","edge-states"]),
83:("Matrix-product belief propagation gives a controlled approximate contraction method for two-dimensional tensor networks. The authors show a quadratic error improvement at comparable effort, relate the method to corner-transfer-matrix and boundary-MPS approaches, and explain when reflection symmetry further simplifies the contraction.","Relevant to classical verification and simulation of quantum many-body states, especially where two-dimensional tensor-network contraction is the bottleneck.",["tensor-networks","many-body-physics","belief-propagation"]),
84:("A draining-vortex analogue reproduces the black-hole-bomb mechanism: surface waves undergo superradiant amplification while a cavity repeatedly reflects them. By varying the confinement and tracking the nonlinear evolution, the experiment determines the late-time state and tests how an instability saturates in a laboratory effective spacetime.","An unusually direct analogue-gravity experiment connecting superradiance, nonlinear dynamics, and black-hole instability physics.",["analogue-gravity","superradiance","black-hole-bomb"]),
88:("Ultracold bosons in an optical quasicrystal are quenched across the superfluid–Bose-glass transition. Fast quenches into the glass produce momentum-space quantum walks, whereas quenches into the superfluid generate real-space spreading with a Lieb–Robinson-like light cone, revealing distinct dynamical signatures of the two phases.","Strong condensed-matter relevance for nonequilibrium localization, quasiperiodic systems, and quantum simulation of disordered many-body dynamics.",["Bose-glass","quantum-quenches","quasicrystals"]),
}
out=["# arXiv Morning Digest — 2026-09-09","","**Categories:** hep-th, quant-ph, cond-mat, gr-qc, hep-ph, physics.atom-ph","**Items found:** 10","**Focus:** quantum gravity, quantum information and computing, many-body physics, cosmology, and high-energy physics",""]
for n,i in enumerate(chosen,1):
 x=src[i]; s,r,t=notes[i]
 out += [f"---\n## {n}. {x['title']}",f"- **Authors:** {', '.join(x['authors'])}",f"- **URL:** {x['id_url'].replace('http:','https:')}",f"- **Categories:** {', '.join(x['categories'])}",f"- **Abstract:** {x['abstract']}",f"- **Summary:** {s}",f"- **Relevance:** {r}",f"- **Tags:** {', '.join(t)}",""]
open('arxiv/2026-09-09.md','w').write('\n'.join(out))
mf='arxiv/manifest.json'; manifest=json.load(open(mf)); manifest.append('arxiv/2026-09-09.md'); open(mf,'w').write(json.dumps(manifest,indent=2)+'\n')
sf='arxiv/seen-urls.json'; seen=json.load(open(sf)); seen += [src[i]['arxiv_id'] for i in chosen if src[i]['arxiv_id'] not in seen]; open(sf,'w').write(json.dumps(seen,indent=2)+'\n')
